/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as SuitesIndexRouteImport } from './routes/suites.index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as SuitesSuiteIdRouteImport } from './routes/suites.$suiteId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesIndexRoute = SuitesIndexRouteImport.update({
  id: '/suites/',
  path: '/suites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesSuiteIdRoute = SuitesSuiteIdRouteImport.update({
  id: '/suites/$suiteId',
  path: '/suites/$suiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/requirements': typeof RequirementsRoute
  '/settings': typeof SettingsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/runs/': typeof RunsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/suites/': typeof SuitesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/requirements': typeof RequirementsRoute
  '/settings': typeof SettingsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/runs': typeof RunsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/suites': typeof SuitesIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/requirements': typeof RequirementsRoute
  '/settings': typeof SettingsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/runs/': typeof RunsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/suites/': typeof SuitesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/requirements'
    | '/settings'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/suites/$suiteId'
    | '/tests/$testId'
    | '/runs/'
    | '/sessions/'
    | '/suites/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/requirements'
    | '/settings'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/suites/$suiteId'
    | '/tests/$testId'
    | '/runs'
    | '/sessions'
    | '/suites'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/requirements'
    | '/settings'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/suites/$suiteId'
    | '/tests/$testId'
    | '/runs/'
    | '/sessions/'
    | '/suites/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  RequirementsRoute: typeof RequirementsRoute
  SettingsRoute: typeof SettingsRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SuitesSuiteIdRoute: typeof SuitesSuiteIdRoute
  TestsTestIdRoute: typeof TestsTestIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SuitesIndexRoute: typeof SuitesIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/': {
      id: '/suites/'
      path: '/suites'
      fullPath: '/suites/'
      preLoaderRoute: typeof SuitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/$suiteId': {
      id: '/suites/$suiteId'
      path: '/suites/$suiteId'
      fullPath: '/suites/$suiteId'
      preLoaderRoute: typeof SuitesSuiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  RequirementsRoute: RequirementsRoute,
  SettingsRoute: SettingsRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SuitesSuiteIdRoute: SuitesSuiteIdRoute,
  TestsTestIdRoute: TestsTestIdRoute,
  RunsIndexRoute: RunsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SuitesIndexRoute: SuitesIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
