/**
 * Outbound-comms neutrality (hard global rule): anything posted to a SHARED/EXTERNAL tracker
 * (Jira/Trello/Plane comments, statuses) must carry NO assistant branding — no "Claude", no "AI",
 * no robot emoji, no "generated by" signatures. Every external adapter runs text through
 * `stripBranding` before sending. The embedded local board is exempt.
 */
const BRANDING_PATTERNS: RegExp[] = [
  // trailing signature first, so "— Claude" is removed wholesale before the bare-word pattern
  /\n*\s*[—-]\s*(claude|ai|your ai assistant)\s*$/gi,
  /co-authored-by:\s*claude[^\n]*/gi,
  /\bgenerated\s+(by|with)\s+(claude(\s+code)?|ai|an?\s+ai\s+assistant)\b/gi,
  /\bclaude(\s+code)?\b/gi,
  /\banthropic\b/gi,
  /\bas\s+an\s+ai\b/gi,
  /\bai[-\s]?(assistant|agent|generated)\b/gi,
  /🤖/g,
]

export function containsBranding(text: string): boolean {
  return BRANDING_PATTERNS.some((re) => {
    re.lastIndex = 0
    return re.test(text)
  })
}

/** Remove assistant branding and collapse the whitespace it leaves behind. */
export function stripBranding(text: string): string {
  let out = text
  for (const re of BRANDING_PATTERNS) out = out.replace(re, '')
  return out
    .replace(/[ \t]{2,}/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\s*[—-]\s*$/, '') // drop any dangling separator left behind
    .trim()
}
