import { describe, expect, it } from 'vitest'
import { JiraAdapter, TrelloAdapter } from './external-adapters'

/** A fake fetch that records calls and returns canned JSON. NO real network. */
function recordingFetch(json: unknown = {}) {
  const calls: { url: string; init?: RequestInit }[] = []
  const f = (async (url: string | URL, init?: RequestInit) => {
    calls.push({ url: String(url), init })
    return {
      json: async () => json,
      text: async () => JSON.stringify(json),
      status: 200,
    } as Response
  }) as unknown as typeof fetch
  return { f, calls }
}

describe('JiraAdapter', () => {
  it('creates an issue with auth + correct endpoint', async () => {
    const { f, calls } = recordingFetch({ key: 'QA-1' })
    const jira = new JiraAdapter({
      baseUrl: 'https://x.atlassian.net',
      email: 'a@b.c',
      token: 't',
      projectKey: 'QA',
      fetchImpl: f,
    })
    const task = await jira.create({ title: 'verify login' })
    expect(task.externalRef).toBe('QA-1')
    expect(calls[0]!.url).toBe('https://x.atlassian.net/rest/api/3/issue')
    const headers = calls[0]!.init!.headers as Record<string, string>
    expect(headers.authorization).toMatch(/^Basic /)
    expect(JSON.parse(calls[0]!.init!.body as string).fields.summary).toBe('verify login')
  })

  it('strips assistant branding before posting a comment', async () => {
    const { f, calls } = recordingFetch({})
    const jira = new JiraAdapter({
      baseUrl: 'https://x.atlassian.net',
      email: 'a@b.c',
      token: 't',
      projectKey: 'QA',
      fetchImpl: f,
    })
    await jira.comment('QA-1', 'Verified ✅ — generated by Claude Code 🤖')
    expect(calls[0]!.url).toBe('https://x.atlassian.net/rest/api/3/issue/QA-1/comment')
    const body = JSON.parse(calls[0]!.init!.body as string).body
    expect(body).toBe('Verified ✅')
    expect(body).not.toMatch(/claude|🤖/i)
  })
})

describe('TrelloAdapter', () => {
  it('creates a card and strips branding on comment — no real network', async () => {
    const { f, calls } = recordingFetch({ id: 'card1' })
    const trello = new TrelloAdapter({ key: 'k', token: 'tok', listId: 'L1', fetchImpl: f })
    const card = await trello.create({ title: 'check API' })
    expect(card.externalRef).toBe('card1')
    expect(calls[0]!.url).toContain('https://api.trello.com/1/cards?')
    expect(calls[0]!.url).toContain('name=check%20API')

    await trello.comment('card1', 'done — Claude')
    expect(calls[1]!.url).toContain('/cards/card1/actions/comments')
    expect(calls[1]!.url).toContain('text=done')
    expect(calls[1]!.url).not.toMatch(/claude/i)
  })
})
