import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { openStore } from '@proba/store'
import type { TaskStatus, TrackerKind } from '@proba/store'
import { migrate } from 'drizzle-orm/better-sqlite3/migrator'
import { describe, expect, it } from 'vitest'
import { ExternalTracker, containsBranding, makeTracker, stripBranding } from './index'
import type { CreateTaskInput, TaskDTO } from './types'

const migrationsFolder = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  'store',
  'migrations',
)

function board() {
  const db = openStore(':memory:')
  migrate(db, { migrationsFolder })
  return makeTracker({ kind: 'embedded', db })
}

describe('EmbeddedTracker', () => {
  it('creates, lists, and transitions tasks on the board', async () => {
    const t = board()
    const task = await t.create({ title: 'verify login flow' })
    expect(task.status).toBe('todo')
    await t.transition(task.id, 'in_progress')
    const inProgress = await t.list('in_progress')
    expect(inProgress.map((x) => x.title)).toContain('verify login flow')
  })
})

describe('stripBranding (outbound neutrality)', () => {
  it('removes assistant branding, keeps the substance', () => {
    expect(containsBranding('Done ✅ — generated by Claude Code 🤖')).toBe(true)
    const cleaned = stripBranding('Login regression fixed.\n\nGenerated with Claude Code 🤖\n— AI')
    expect(cleaned).toBe('Login regression fixed.')
    expect(containsBranding(cleaned)).toBe(false)
  })
  it('leaves a neutral message untouched', () => {
    const msg = 'Smoke test passed on staging; attaching screenshot.'
    expect(stripBranding(msg)).toBe(msg)
  })
})

describe('ExternalTracker', () => {
  it('neutralizes branding before any outbound post', async () => {
    const posted: string[] = []
    class FakeJira extends ExternalTracker {
      readonly kind: TrackerKind = 'jira'
      async list(): Promise<TaskDTO[]> {
        return []
      }
      async create(i: CreateTaskInput): Promise<TaskDTO> {
        return { id: 'J-1', title: i.title, status: 'todo' as TaskStatus }
      }
      async transition(id: string, status: TaskStatus): Promise<TaskDTO> {
        return { id, title: 't', status }
      }
      protected async post(_id: string, neutralBody: string): Promise<void> {
        posted.push(neutralBody)
      }
    }
    const jira = new FakeJira()
    await jira.comment('J-1', 'Fix verified 🤖 — Claude')
    expect(posted[0]).toBe('Fix verified')
    expect(containsBranding(posted[0]!)).toBe(false)
  })
})

describe('makeTracker', () => {
  it('throws an honest error for unconfigured external trackers', () => {
    expect(() => makeTracker({ kind: 'trello' })).toThrow(/not configured/i)
  })
})
